## Numpy

### Задание 1

In [1]:
import numpy as np

In [20]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [21]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [22]:
mean_a = np.array(a.mean(axis=0))

In [23]:
mean_a

array([2. , 8.4])

### Задание 2

In [25]:
a_centered = a - mean_a

In [26]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [27]:
a_centered_t = np.transpose(a_centered)

In [28]:
a_centered_t

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [33]:
a_centered_sp = a_centered_t[0, :] @ a_centered_t[1, :]

In [36]:
a_centered_sp / (5-1)

2.0

### Задание 4

In [35]:
np.cov(a_centered_t)

array([[1. , 2. ],
       [2. , 4.3]])

## Pandas

### Задание 1

In [37]:
import pandas as pd

In [38]:
a = {
    "author_id": [1, 2, 3],
    "author_name": ["Тургенев", "Чехов", "Островский"]
}

authors = pd.DataFrame(a)

In [39]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [41]:
b = {
     "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
}

books = pd.DataFrame(b)

In [42]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Задание 2

In [43]:
authors_price = pd.merge(authors, books, on='author_id', how='inner')

In [44]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Задание 3

In [45]:
top5 = authors_price.nlargest(5, "price")## Задание 2

In [46]:
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

### Задание 4

In [55]:
authors_stat = pd.DataFrame({
    "author_name": authors_price["author_name"].unique()### Задание 3,
    "min_price": authors_price["price"].max(),
    "max_price": authors_price["price"].min(),
    "mean_price": authors_price["price"].mean()
})

In [57]:
authors_stat

author_name  min_price  max_price  mean_price
0    Тургенев        500        290  387.142857
1       Чехов        500        290  387.142857
2  Островский        500        290  387.142857

### Задание 5

In [71]:
?pd.pivot_table

In [69]:
authors_price["cover"] = pd.Series(['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'], index=None)


In [70]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [75]:
covers_price = pd.pivot_table(authors_price, values='price', index=['author_name'],
...                     columns=['cover'], aggfunc=np.sum)

In [81]:
covers_price["мягкая"] = covers_price["мягкая"].fillna(0)

In [84]:
covers_price["твердая"] = covers_price["твердая"].fillna(0)

In [85]:
covers_price

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [89]:
covers_price.to_pickle("book_info.pkl")

In [90]:
book_info2 = pd.read_pickle("book_info.pkl")

In [91]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True